pipeline {
    
    agent any
    
    environment {
        
        CONTAINER_REGISTRY = "ghcr.io/landon-hotel-kevin/"
        ARTIFACT_ID = readMavenPom().getArtifactId()
        JAR_NAME = "${ARTIFACT_ID}-${BUILD_NUMBER}"
        JAR_LOCATION = "target/${JAR_NAME}.jar"
        IMAGE_NAME = "${ARTIFACT_ID}:${BUILD_NUMBER}"
        

    }
    
	stages {
	    
	    stage("Build Application"){
	    
	    	agent{
	    		
	    		docker {
	    		
	    			image "openjdk:11"
	    			
	    		}
	    	}
	    
	        steps {
	        	sh "echo Performing Maven build: ${ARTIFACT_ID}"
	        	sh "./mvnw -DjarName=${JAR_NAME} clean verify"        	    
        	}
	        
	    }
	    
	    stage("Build Container Image"){
	    	
	    	steps {    	    
		        sh "echo Building container image: ${IMAGE_NAME}"
	    	}    
	        
	    }

	    stage("Publish Container Image"){
			
			steps{
		        sh "echo Publishing container image to: ${CONTAINER_REGISTRY}"		
			}	        
	        
	    }

	}       
}