pipeline {

    options {
    	disableConcurrentBuilds()
        overrideIndexTriggers(false)
    }   

    agent any
    
    parameters {
        string(name: 'IMAGE_TAG')
        string(name: 'VERSION')
    }
    
    environment {
    	
    	GITHUB_DEPLOY_REPO_URL = "git@github.com:javacd-workspace/javacd-deploy-kustomize.git"
    	
    }
    
    stages {
        
        stage('Deploy to Staging'){
        
         steps {
         
                git url: "${GITHUB_DEPLOY_REPO_URL}", credentialsId: 'github-ssh-key', branch: 'main'
             
                sh 'git config user.email "pipeline@linkedin.com"'
  				sh 'git config user.name "Pipeline"'
  				
                sh "cd base && kustomize edit set image ${IMAGE_TAG}=${IMAGE_TAG}:${VERSION}" 
                
                sh 'git commit -am "Updated image ${IMAGE_TAG} to ${VERSION}"'
                
                sshagent(['github-ssh-key']) {
  					sh "git push origin main"
				}
            }
        }
        
        stage('Acceptance Testing'){
        
          steps{
                sh 'echo "TODO: Add additional testing"'
          }
          
        }
        
        
        stage('Deploy to Production'){
        
         steps {
         
                git url: "${GITHUB_DEPLOY_REPO_URL}", credentialsId: 'github-ssh-key', branch: 'release'
             
                sh 'git config user.email "pipeline@linkedin.com"'
  				sh 'git config user.name "Pipeline"'
  				
                sh 'git merge main'
                
                sshagent(['github-ssh-key']) {
  					sh "git push origin release"
				}
            }
          
        }
        
    }
}